apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mamaloo-dev
  namespace: argocd
  labels:
    app: mamaloo
    environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/Analarie/Portal-Mamaloo-desenvolvimento.git'
    targetRevision: main
    path: helm/mamaloo-app
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: namespace
          value: mamaloo-dev
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mamaloo-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
